In [4]:
import numpy as np
import pandas as pd
from gensim.models import Word2Vec

In [3]:
tokenized_sentence = [['Hello', 'this', 'is', 'python', 'training', 'by', 'Aman'],
                     ['Hello', 'this', 'is', 'java', 'training', 'by', 'Aman'],
                     ['Hello', 'this', 'is', 'Data Science', 'training', 'by', 'unfold', 'Data', 'science'],
                     ['Hello', 'this', 'is', 'programming', 'training', '']]

In [5]:
#training word2vec

mymodel = Word2Vec(tokenized_sentence, min_count = 1)

In [6]:
print(mymodel)

Word2Vec(vocab=14, size=100, alpha=0.025)


In [8]:
words = list(mymodel.wv.vocab)

print(words)

['Hello', 'this', 'is', 'python', 'training', 'by', 'Aman', 'java', 'Data Science', 'unfold', 'Data', 'science', 'programming', '']


In [12]:
print(mymodel['Hello'])

[-0.00301687  0.00264102  0.00319383  0.00228811  0.00299492  0.00480412
 -0.00101683  0.00412398 -0.00389662 -0.00450724 -0.00482626 -0.00117881
 -0.00460529 -0.00115099  0.00114765 -0.00457821  0.00231652 -0.00265483
  0.00368051 -0.00090518  0.00245863  0.00055421 -0.0036428  -0.00218155
 -0.00087151  0.0003536   0.00088714  0.00206593 -0.00297591 -0.00109891
 -0.00130623  0.00185955  0.00226752  0.00097536 -0.00099665  0.00355611
  0.004166   -0.00343716  0.00355046 -0.00184526  0.00259758 -0.00131937
 -0.00052313  0.00400841  0.00095502  0.00442086 -0.00359578  0.00171602
 -0.00460347  0.00284757 -0.00235986  0.00399665 -0.00135034  0.00148057
 -0.00450972 -0.00179162 -0.00263197  0.00180473 -0.00281323  0.00250759
  0.00489149  0.00464239  0.00300893  0.00181023  0.00272141 -0.00060971
 -0.00455504  0.00168438 -0.00336344 -0.00060874  0.00171925 -0.00462814
 -0.00109115 -0.00478454 -0.00065295 -0.00144504  0.00437326  0.00263299
  0.00214796 -0.00220037  0.00027245  0.00056722 -0

<ipython-input-12-3b9cac13c222>:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  print(mymodel['Hello'])


In [16]:
mymodel.wv.most_similar('Data')

[('Hello', 0.17398984730243683),
 ('by', 0.09012329578399658),
 ('this', 0.03842597082257271),
 ('Data Science', 0.02923613414168358),
 ('science', 0.023316582664847374),
 ('unfold', -0.014441132545471191),
 ('java', -0.027739744633436203),
 ('is', -0.04176836460828781),
 ('programming', -0.05720347911119461),
 ('Aman', -0.0662764310836792)]

## Create Word Embedding using Keras

In [17]:
import numpy as np
import pandas as pd
from keras.layers import Dense, Flatten
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences

In [41]:
sent = ['hello, how are you',
       'how are you',
       'how are you doing',
       'I am doing great',
       'I am doing good',
       'I am good']

sent_labels = [1,1,1,0,0,0]

In [42]:
my_vocab_size = 30
encoded_sent = [one_hot(i, my_vocab_size) for i in sent]
print(encoded_sent)

[[14, 8, 5, 15], [8, 5, 15], [8, 5, 15, 9], [10, 29, 9, 20], [10, 29, 9, 20], [10, 29, 20]]


In [43]:
length = 5
padded_sent = pad_sequences(encoded_sent, maxlen=length, padding='pre')
print(padded_sent)
padded_sent.shape

[[ 0 14  8  5 15]
 [ 0  0  8  5 15]
 [ 0  8  5 15  9]
 [ 0 10 29  9 20]
 [ 0 10 29  9 20]
 [ 0  0 10 29 20]]


(6, 5)

In [44]:
mymodel = Sequential()
mymodel.add(Embedding(my_vocab_size, 8, input_length = length))
mymodel.add(Flatten())
mymodel.add(Dense(1, activation = 'sigmoid'))

In [45]:
mymodel.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [47]:
mymodel.fit(np.asarray(padded_sent), np.asarray(sent_labels), epochs = 30)

Epoch 1/30
1/1 [==============================] - 1s 1s/step - loss: 0.6764 - accuracy: 0.8333
Epoch 2/30
1/1 [==============================] - 0s 0s/step - loss: 0.6743 - accuracy: 0.8333
Epoch 3/30
1/1 [==============================] - 0s 12ms/step - loss: 0.6722 - accuracy: 1.0000
Epoch 4/30
1/1 [==============================] - 0s 7ms/step - loss: 0.6701 - accuracy: 1.0000
Epoch 5/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6679 - accuracy: 1.0000
Epoch 6/30
1/1 [==============================] - 0s 0s/step - loss: 0.6658 - accuracy: 1.0000
Epoch 7/30
1/1 [==============================] - 0s 0s/step - loss: 0.6637 - accuracy: 1.0000
Epoch 8/30
1/1 [==============================] - 0s 2ms/step - loss: 0.6616 - accuracy: 1.0000
Epoch 9/30
1/1 [==============================] - 0s 1ms/step - loss: 0.6595 - accuracy: 1.0000
Epoch 10/30
1/1 [==============================] - 0s 321us/step - loss: 0.6574 - accuracy: 1.0000
Epoch 11/30
1/1 [=======================

In [48]:
vocab_size = 30
mysent_to_predict = ['How are you suman', 'I am good']

encoded = [one_hot(i,vocab_size)for i in mysent_to_predict]
my_padded = pad_sequences(encoded, padding = 'pre', maxlen = length)

In [49]:
my_padded

array([[ 0,  8,  5, 15,  8],
       [ 0,  0, 10, 29, 20]])

In [61]:
mymodel.predict_classes(my_padded)

array([[1],
       [0]])