In [1]:
import numpy as np
import pandas as pd
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

In [2]:
glove_embedding = WordEmbeddings('glove')

2021-02-11 16:03:30,193 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to C:\Users\laksh\AppData\Local\Temp\tmpvbddncvu


100%|█████████████████████████████████████████████████████████████████| 160000128/160000128 [18:28<00:00, 144395.56B/s]

2021-02-11 16:21:59,770 copying C:\Users\laksh\AppData\Local\Temp\tmpvbddncvu to cache at C:\Users\laksh\.flair\embeddings\glove.gensim.vectors.npy
2021-02-11 16:21:59,845 removing temp file C:\Users\laksh\AppData\Local\Temp\tmpvbddncvu


2021-02-11 16:22:01,798 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to C:\Users\laksh\AppData\Local\Temp\tmp7si1h876


100%|███████████████████████████████████████████████████████████████████| 21494764/21494764 [01:18<00:00, 272334.28B/s]

2021-02-11 16:23:21,563 copying C:\Users\laksh\AppData\Local\Temp\tmp7si1h876 to cache at C:\Users\laksh\.flair\embeddings\glove.gensim
2021-02-11 16:23:21,583 removing temp file C:\Users\laksh\AppData\Local\Temp\tmp7si1h876


In [3]:
sentence_1 = Sentence('apple release iphone 12 pro max in 2020')

In [4]:
glove_embedding.embed(sentence_1)

[Sentence: "apple release iphone 12 pro max in 2020"   [− Tokens: 8]]

In [9]:
for token in sentence_1:
    print(token)
    print(token.embedding)
    print('\n')

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [10]:
sentence_1[0]

Token: 1 apple

In [11]:
sentence_1[0].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [13]:
sentence_1[0].embedding.shape

torch.Size([100])

In [19]:
sentence_2 = Sentence('an apple a day keep the doctor away')
glove_embedding.embed(sentence_2)

[Sentence: "an apple a day keep the doctor away"   [− Tokens: 8]]

In [20]:
sentence_2[1]

Token: 2 apple

In [21]:
sentence_2[1].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [23]:
for token in sentence_2:
    print(token)
    print(token.embedding)
    print('\n')

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [25]:
#Glove distance between the same the words.

distance.euclidean(sentence_1[0].embedding, sentence_2[1].embedding)

0.0

In [28]:
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/714M [00:00<?, ?B/s]

In [29]:
bert_embedding.embed(sentence_1)

for token in sentence_1:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.5671,  0.1750,  0.2552])


Token: 2 release
tensor([-0.0097, -0.8005,  0.4212,  ...,  1.0225,  0.1483,  0.7030])


Token: 3 iphone
tensor([-0.3609, -0.5975,  0.5235,  ...,  1.0469,  0.1202, -0.6818])


Token: 4 12
tensor([ 0.0730,  0.1813,  0.0204,  ...,  1.2685,  0.2502, -0.0633])


Token: 5 pro
tensor([-0.2332,  0.1988, -0.2101,  ...,  1.8373,  0.7664, -0.3786])


Token: 6 max
tensor([ 0.3356,  0.1247,  0.2099,  ...,  1.3346, -0.2988,  0.3212])


Token: 7 in
tensor([ 0.0857, -0.2220,  0.1657,  ...,  1.4881, -0.3500, -0.2911])


Token: 8 2020
tensor([-0.1241,  0.3447,  0.9852,  ...,  0.7934,  1.0940, -0.3618])




In [30]:
bert_embedding.embed(sentence_2)
for token in sentence_2:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624,  ...,  1.2540,  0.8841,  0.1080])


Token: 2 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.8441,  1.0448,  0.2320])


Token: 3 a
tensor([-0.2709,  0.0440, -0.0203,  ...,  1.0410, -0.4765,  0.5495])


Token: 4 day
tensor([-0.3669,  0.4154,  0.1348,  ...,  1.0299,  0.0429,  0.0841])


Token: 5 keep
tensor([-0.2415, -0.1409,  0.2783,  ..., -0.2443,  0.2055, -0.4389])


Token: 6 the
tensor([-0.0382, -0.2449,  0.7281,  ..., -0.3797, -0.3490,  0.3054])


Token: 7 doctor
tensor([ 0.0432, -0.4753,  0.1581,  ...,  0.5781,  0.2785,  0.2263])


Token: 8 away
tensor([-0.1038, -0.0148,  0.5993,  ...,  1.0562,  0.2152,  0.1576])




In [33]:
distance.euclidean(np.array(sentence_1[0].embedding), np.array(sentence_2[1].embedding))

44.95234298706055