In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences ###
sent = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#Initialise the vocabulary size

voc_size = 10000

### One hot Representation

In [5]:
onehot_repr = [one_hot(word, voc_size) for word in sent]

onehot_repr

[[5238, 7981, 3807, 8609],
 [5238, 7981, 3807, 803],
 [5238, 5087, 3807, 6168],
 [3933, 414, 6028, 4274, 465],
 [3933, 414, 6028, 4274, 3730],
 [6820, 5238, 8775, 3807, 6567],
 [8549, 5405, 5083, 4274]]

### Word Embedding Representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedding_doc = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedding_doc)

[[   0    0    0    0 5238 7981 3807 8609]
 [   0    0    0    0 5238 7981 3807  803]
 [   0    0    0    0 5238 5087 3807 6168]
 [   0    0    0 3933  414 6028 4274  465]
 [   0    0    0 3933  414 6028 4274 3730]
 [   0    0    0 6820 5238 8775 3807 6567]
 [   0    0    0    0 8549 5405 5083 4274]]


In [9]:
#deimension = 10

model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam', 'mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedding_doc))

[[[-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027
   -0.00872191  0.02827761  0.03758368  0.01368925  0.04667265]
  [-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027
   -0.00872191  0.02827761  0.03758368  0.01368925  0.04667265]
  [-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027
   -0.00872191  0.02827761  0.03758368  0.01368925  0.04667265]
  [-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027
   -0.00872191  0.02827761  0.03758368  0.01368925  0.04667265]
  [ 0.02068392  0.0096459   0.0132818   0.01347302 -0.02017603
    0.04967364 -0.02419906 -0.01471285  0.02893169 -0.0305711 ]
  [-0.00266001  0.01921624  0.01613266  0.00334165 -0.00508691
   -0.02285182 -0.02901857  0.02680962  0.04063758  0.01097482]
  [-0.03674211  0.0091512   0.01318968 -0.01908712  0.00109522
    0.00735598 -0.0335141   0.02623551  0.02755268 -0.01793125]
  [-0.02367139  0.01349015 -0.02403592  0.02337218  0.0076346
   -0.03266721 -0.04632306 -0.01862105 -0.0414776

In [12]:
embedding_doc[0]

array([   0,    0,    0,    0, 5238, 7981, 3807, 8609])

In [13]:
print(model.predict(embedding_doc)[0])

[[-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027 -0.00872191
   0.02827761  0.03758368  0.01368925  0.04667265]
 [-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027 -0.00872191
   0.02827761  0.03758368  0.01368925  0.04667265]
 [-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027 -0.00872191
   0.02827761  0.03758368  0.01368925  0.04667265]
 [-0.025102    0.00236345 -0.03877796  0.02933499  0.00406027 -0.00872191
   0.02827761  0.03758368  0.01368925  0.04667265]
 [ 0.02068392  0.0096459   0.0132818   0.01347302 -0.02017603  0.04967364
  -0.02419906 -0.01471285  0.02893169 -0.0305711 ]
 [-0.00266001  0.01921624  0.01613266  0.00334165 -0.00508691 -0.02285182
  -0.02901857  0.02680962  0.04063758  0.01097482]
 [-0.03674211  0.0091512   0.01318968 -0.01908712  0.00109522  0.00735598
  -0.0335141   0.02623551  0.02755268 -0.01793125]
 [-0.02367139  0.01349015 -0.02403592  0.02337218  0.0076346  -0.03266721
  -0.04632306 -0.01862105 -0.04147769 -0.04940739]]